/**
 * Vendors a curated subset of Material Icon Theme file icons into the app.
 *
 * Usage:
 *   git clone https://github.com/material-extensions/vscode-material-icon-theme /tmp/mit
 *   git -C /tmp/mit checkout 850c06c7fb7ea73d873a0ce2f966bbd20850946d
 *   bun apps/desktop/scripts/generate-file-icons.ts /tmp/mit
 *
 * Writes public/file-icons/*.svg and src/lib/fileIconMap.ts.
 * They live in public/ rather than src/assets/ so the bundler never sees ~290
 * extra modules — an eager import.meta.glob pulled them into every component
 * test's module graph and timed the vitest workers out.
 * The npm package can't drive this: it ships only a flattened manifest, and the
 * curation below depends on upstream's popularity ordering in fileIcons.ts.
 */
import { existsSync } from "node:fs";
import { copyFile, mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import path from "node:path";

const UPSTREAM_VERSION = "5.37.0";
const UPSTREAM_COMMIT = "850c06c7fb7ea73d873a0ce2f966bbd20850946d";

/** Upstream orders icons by popularity; the first N cover almost every repo. */
const CORE_COUNT = 300;

/** Past the cutoff but central to the stacks we open. */
const ADDED = [
  "biome",
  "bun",
  "drizzle",
  "makefile",
  "php",
  "pnpm",
  "prisma",
  "svelte",
  "tailwindcss",
  "tauri",
  "tsconfig",
  "vite",
  "vitest",
];

interface UpstreamIcon {
  name: string;
  fileExtensions?: string[];
  fileNames?: string[];
  /** Generated recolor of another icon — no standalone SVG to vendor. */
  clone?: unknown;
  /** Gated behind an opt-in icon pack (angular, react_redux, …). */
  enabledFor?: string[];
}

const fail = (message: string): never => {
  console.error(`generate-file-icons: ${message}`);
  process.exit(1);
};

const upstream = process.argv[2];
if (!upstream) fail("pass the path to a vscode-material-icon-theme checkout");

const upstreamRoot = path.resolve(upstream);
const pkgPath = path.join(upstreamRoot, "package.json");
if (!existsSync(pkgPath)) fail(`no package.json at ${upstreamRoot}`);

const pkg: { version?: string } = JSON.parse(await readFile(pkgPath, "utf8"));
if (pkg.version !== UPSTREAM_VERSION) {
  fail(
    `checkout is ${pkg.version}, expected ${UPSTREAM_VERSION} (commit ${UPSTREAM_COMMIT}) — ` +
      "bump the pin deliberately, then re-run",
  );
}

const iconsModule: { fileIcons: { icons: UpstreamIcon[] } } = await import(
  path.join(upstreamRoot, "src/core/icons/fileIcons.ts")
);
const all = iconsModule.fileIcons.icons;

const added = new Set(ADDED);
const missing = ADDED.filter((name) => !all.some((icon) => icon.name === name));
if (missing.length) fail(`ADDED names not in upstream: ${missing.join(", ")}`);

const selected = all.filter(
  (icon, index) =>
    (index < CORE_COUNT || added.has(icon.name)) && !icon.clone && !icon.enabledFor,
);

const outRoot = path.resolve(import.meta.dirname, "..");
const assetDir = path.join(outRoot, "public/file-icons");

await mkdir(assetDir, { recursive: true });
for (const stale of await readdir(assetDir)) {
  if (stale.endsWith(".svg")) await rm(path.join(assetDir, stale));
}

// Upstream's default "file" icon is generated at publish time, so it isn't in a
// checkout — synthesize it here rather than depend on the npm tarball.
await writeFile(
  path.join(assetDir, "file.svg"),
  '<svg viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg">' +
    '<path fill="#90a4ae" d="M13 9h5.5L13 3.5V9M6 2h8l6 6v12a2 2 0 0 1-2 2H6a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2m9 16v-2H6v2h9m3-4v-2H6v2h12Z"/>' +
    "</svg>\n",
);

// The app is dark-only, so upstream's _light variants are skipped.
for (const icon of selected) {
  const svg = path.join(upstreamRoot, "icons", `${icon.name}.svg`);
  if (!existsSync(svg)) fail(`missing SVG for "${icon.name}"`);
  await copyFile(svg, path.join(assetDir, `${icon.name}.svg`));
}

const fileNames = new Map<string, string>();
const pathNames = new Map<string, string>();
const fileExtensions = new Map<string, string>();

// Later entries win, matching how upstream resolves overlapping claims.
for (const icon of selected) {
  for (const name of icon.fileNames ?? []) {
    const key = name.toLowerCase();
    (key.includes("/") ? pathNames : fileNames).set(key, icon.name);
  }
  for (const ext of icon.fileExtensions ?? []) {
    fileExtensions.set(ext.toLowerCase(), icon.name);
  }
}

const emit = (name: string, map: Map<string, string>) => {
  const entries = [...map]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([key, icon]) => `  ${JSON.stringify(key)}: ${JSON.stringify(icon)},`)
    .join("\n");
  return `export const ${name}: Record<string, string> = {\n${entries}\n}\n`;
};

await writeFile(
  path.join(outRoot, "src/lib/fileIconMap.ts"),
  [
    `// Generated by scripts/generate-file-icons.ts from material-icon-theme ${UPSTREAM_VERSION}`,
    `// (commit ${UPSTREAM_COMMIT}). Do not edit by hand.`,
    "",
    emit("FILE_NAMES", fileNames),
    emit("PATH_NAMES", pathNames),
    emit("FILE_EXTENSIONS", fileExtensions),
  ].join("\n"),
);

await copyFile(path.join(upstreamRoot, "LICENSE"), path.join(assetDir, "LICENSE"));
await writeFile(
  path.join(assetDir, "NOTICE"),
  [
    "Icons in this directory are a curated subset of Material Icon Theme",
    `${UPSTREAM_VERSION} (commit ${UPSTREAM_COMMIT}), MIT licensed.`,
    "https://github.com/material-extensions/vscode-material-icon-theme",
    "",
    "Regenerate with scripts/generate-file-icons.ts; do not edit by hand.",
    "",
  ].join("\n"),
);

console.log(
  `${selected.length} icons, ${fileNames.size} names, ${pathNames.size} paths, ${fileExtensions.size} extensions`,
);
