import { describe, expect, it } from "vitest";
import { parseTranscript, parseTranscriptUsage } from "@/hooks/useAgentChat";

/** Build a transcript from JSONL records, the way Claude Code writes one. */
const transcript = (...records: unknown[]) =>
  records.map((r) => JSON.stringify(r)).join("\n") + "\n";

const userText = (text: string) => ({
  type: "user",
  message: { role: "user", content: text },
});

const assistant = (...content: unknown[]) => ({
  type: "assistant",
  message: { role: "assistant", content },
});

describe("parseTranscript", () => {
  it("returns nothing for an empty transcript", () => {
    expect(parseTranscript("")).toEqual([]);
    expect(parseTranscript("\n\n  \n")).toEqual([]);
  });

  it("skips lines that are not JSON instead of failing the whole parse", () => {
    const text = "not json\n" + transcript(userText("hello"));
    expect(parseTranscript(text).map((m) => m.text)).toEqual(["hello"]);
  });

  it("reads a plain-string user turn", () => {
    const [msg] = parseTranscript(transcript(userText("hello")));
    expect(msg).toMatchObject({ role: "user", text: "hello", streaming: false });
  });

  it("concatenates text blocks of an array-form user turn", () => {
    const text = transcript({
      type: "user",
      message: {
        role: "user",
        content: [
          { type: "text", text: "one " },
          { type: "text", text: "two" },
        ],
      },
    });
    expect(parseTranscript(text)[0].text).toBe("one two");
  });

  it("drops the meta turns Claude Code injects as user messages", () => {
    const synthetic = [
      "<local-command-stdout>ok</local-command-stdout>",
      "<command-name>/clear</command-name>",
      "<bash-input>ls</bash-input>",
      "<user-prompt-submit-hook>hi</user-prompt-submit-hook>",
      "<task-notification>done</task-notification>",
      "<system-reminder>note</system-reminder>",
      "Caveat: The messages below were generated by the user",
    ];
    const text = transcript(...synthetic.map(userText), userText("real input"));
    expect(parseTranscript(text).map((m) => m.text)).toEqual(["real input"]);
  });

  it("ignores sidechain (subagent) records", () => {
    const text = transcript(
      { ...userText("subagent turn"), isSidechain: true },
      userText("main turn")
    );
    expect(parseTranscript(text).map((m) => m.text)).toEqual(["main turn"]);
  });

  it("splits an assistant turn into text, thinking and tools", () => {
    const text = transcript(
      assistant(
        { type: "thinking", thinking: "considering" },
        { type: "text", text: "Here goes." },
        { type: "tool_use", id: "t1", name: "Read", input: { file_path: "/a.ts" } }
      )
    );
    const [msg] = parseTranscript(text);
    expect(msg).toMatchObject({
      role: "assistant",
      text: "Here goes.",
      thinking: "considering",
    });
    expect(msg.tools).toEqual([
      { id: "t1", name: "Read", input: { file_path: "/a.ts" }, partial: "" },
    ]);
  });

  it("attaches a tool result to the call it belongs to", () => {
    const text = transcript(
      assistant({ type: "tool_use", id: "t1", name: "Read", input: {} }),
      {
        type: "user",
        message: {
          role: "user",
          content: [
            { type: "tool_result", tool_use_id: "t1", content: "file contents" },
          ],
        },
      }
    );
    const [msg] = parseTranscript(text);
    expect(msg.tools[0]).toMatchObject({ result: "file contents", isError: false });
  });

  it("marks an errored tool result and stringifies non-string content", () => {
    const text = transcript(
      assistant({ type: "tool_use", id: "t1", name: "Bash", input: {} }),
      {
        type: "user",
        message: {
          role: "user",
          content: [
            {
              type: "tool_result",
              tool_use_id: "t1",
              content: [{ type: "text", text: "boom" }],
              is_error: true,
            },
          ],
        },
      }
    );
    const [tool] = parseTranscript(text)[0].tools;
    expect(tool.isError).toBe(true);
    expect(tool.result).toBe('[{"type":"text","text":"boom"}]');
  });

  it("ignores a tool result whose call is not in the transcript", () => {
    const text = transcript({
      type: "user",
      message: {
        role: "user",
        content: [{ type: "tool_result", tool_use_id: "gone", content: "x" }],
      },
    });
    expect(parseTranscript(text)).toEqual([]);
  });

  it("drops an assistant turn with no content of any kind", () => {
    expect(parseTranscript(transcript(assistant()))).toEqual([]);
  });

  it("gives every message a distinct id", () => {
    const text = transcript(userText("a"), userText("b"), userText("c"));
    const ids = parseTranscript(text).map((m) => m.id);
    expect(new Set(ids).size).toBe(3);
  });

  it("preserves conversation order across turns", () => {
    const text = transcript(
      userText("q"),
      assistant({ type: "text", text: "a" }),
      userText("q2")
    );
    expect(parseTranscript(text).map((m) => m.role)).toEqual([
      "user",
      "assistant",
      "user",
    ]);
  });
});

describe("parseTranscriptUsage", () => {
  const turn = (input: number, output: number, model = "claude-sonnet-4-5") => ({
    type: "assistant",
    message: {
      role: "assistant",
      model,
      content: [],
      usage: { input_tokens: input, output_tokens: output },
    },
  });

  it("sums tokens across assistant turns", () => {
    const usage = parseTranscriptUsage(transcript(turn(10, 5), turn(20, 7)));
    expect(usage).toMatchObject({ inputTokens: 30, outputTokens: 12 });
  });

  it("reports the last model seen", () => {
    const usage = parseTranscriptUsage(
      transcript(turn(1, 1, "claude-sonnet-4-5"), turn(1, 1, "claude-opus-4-8"))
    );
    expect(usage.model).toBe("claude-opus-4-8");
  });

  it("excludes sidechain turns from the totals", () => {
    const usage = parseTranscriptUsage(
      transcript({ ...turn(100, 100), isSidechain: true }, turn(1, 2))
    );
    expect(usage).toMatchObject({ inputTokens: 1, outputTokens: 2 });
  });

  it("ignores user turns and unparseable lines", () => {
    const text = "garbage\n" + transcript(userText("hi"), turn(4, 5));
    expect(parseTranscriptUsage(text)).toMatchObject({
      inputTokens: 4,
      outputTokens: 5,
    });
  });

  it("returns zeroed totals and no model for an empty transcript", () => {
    expect(parseTranscriptUsage("")).toEqual({
      model: undefined,
      inputTokens: 0,
      outputTokens: 0,
    });
  });

  it("treats a turn with no usage block as contributing nothing", () => {
    const text = transcript({
      type: "assistant",
      message: { role: "assistant", model: "claude-opus-4-8", content: [] },
    });
    expect(parseTranscriptUsage(text)).toMatchObject({
      model: "claude-opus-4-8",
      inputTokens: 0,
    });
  });
});
